[package]
name = "cli-client"
version = "0.1.0"
authors = ["Fredrik Simonsson <simson@thesimson.net>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
simple-error = "0.2"
reqwest = { version = "0.10", features = ["blocking","json"] }
serde = { version = "1.0", features = ["derive"] }
